### ISSUE TITLE
Failed parsing SMILES

### ISSUE THREAD

**Issue by zengzishuo** [SysBioChalmers/DLKcat#13]
Hi,

I encountered "SMILES Parse Error"::

"SMILES Parse Error: syntax error while parsing: Naphthalene-1,6-diol"
"SMILES Parse Error: Failed parsing SMILES 'Naphthalene-1,6-diol' for input: 'Naphthalene-1,6-diol'"

The substrate name is "Naphthalene-1,6-diol". **The SMILES of my substrate is "C1=CC2=C(C=CC(=C2)O)C(=C1)O", I don't know what's wrong with this SMILES.** 

Protein sequence is 

"MSEAADVERVYAAMEEAAGLLGVACARDKIYPLLSTFQDTLVEGGSVVVFSMASGRHSTELDFSISVPTSHGDPYATVVEKGLFPATGHPVDDLLADTQKHLPVSMFAIDGEVTGGFKKTYAFFPTDNMPGVAELSAIPSMPPAVAENAELFARYGLDKVQMTSMDYKKRQVNLYFSELSAQTLEAESVLALVRELGLHVPNELGLKFCKRSFSVYPTLNWETGKIDRLCFSVISNDPTLVPSSDEGDIEKFHNYATKAPYAYVGEKRTLVYGLTLSPKEEYYKLGAYYHITDVQRGLLKAFDSLED"

I tried inputting only substrate name or only substrate SMILES, neither worked.

Please help. Thanks

**Comment by le-yuan** [comment]
If you use the substrate SMILES as the input, definitely no such kind of warning or error. While if your predicted Kcat is "None", maybe you need to check the previous issue and solution here: https://github.com/SysBioChalmers/DLKcat/issues/5.

**Comment by feiranl** [comment]
Hi, it works fine from my side either with the substrate name `Naphthalene-1,6-diol` and the substrate SMILEs `C1=CC2=C(C=CC(=C2)O)C(=C1)O`. If you still have this issue, I suggest you check the `input.tsv` file by opening it using excel,  you may mistakenly use `space` rather than the `tab` as the delimiter.
