### ISSUE TITLE
RMSE and data

### ISSUE THREAD

**Issue by jiejiangtao** [SysBioChalmers/DLKcat#25]
Dear researcher，
      I have two questions. One is  from the code I can see that the input is sequence and smile，but I find that some data has the same sequence and smile。 
    The other is that I found that kcat in the code passed the log2 conversion，But the graphs in this article are all log10 transforms

**Comment by feiranl** [comment]
Hi, thanks for asking! Could you tell which file did you see the duplicate datapoints?
Yes. We trained the model with log2 conversion, and in the paper to facilitate comparisons with other papers( most of them are based on log10), then we did the transform when we plotting

**Comment by jiejiangtao** [comment]
![image](https://github.com/SysBioChalmers/DLKcat/assets/77655347/4e3e4302-80ae-4b82-8148-8be365ef8809)
The code predicts the kcat value through sequence and substrate. My understanding is that data should be de-weighted through sequence and substrate. As I said above, I found that some data smile and SEQUENCE are identical in the data you provided。

**Comment by jiejiangtao** [comment]
That's my understanding. I don't know if that's right。Thanks

**Comment by le-yuan** [comment]
Hi, thanks for your question. I suppose that I know the answer about your question. 

I checked the original data in this repo. For these very few duplicated datapoints with the same protein sequence and substrate SMILES in different entries, they were generated mainly due to the the circumstance when different kinds of data were combined together  from different resources. In that step, we still didn't have all the protein sequence for all entries. So we used EC Number, organism info and substrate info to evaluate whether there are duplicated entries.

For example, I checked that there are two entries which have the same protein sequence (MKRINALTIAGTDPSGGAGIQADLKTFSALGAYGCSVITALVAQNTRGVQSVYRIEPDFVAAQLDSVFSDVRIDTTKIGMLAETDIVEAVAERLQRYQIQNVVLDTVMLAKSGDPLLSPSAVATLRSRLLPQVSLITPNLPEAAALLDAPHARTEQEMLEQGRSLLAMGCGAVLMKGGHLDDEQSPDWLFTREGEQRFTAPRIMTKNTHGTGCTLSAALAALRPRHTNWADTVQEAKSWLSSALAQADTLEVGHGIGPVHHFHAWW) and substrate SMILES (CC1=NC=C(C(=N1)N)CO). 

These are two entries shown as below:
{'ECNumber': '2.7.1.49', 'Organism': 'Escherichia coli', 'Smiles': 'CC1=NC=C(C(=N1)N)CO', 'Substrate': '2-methyl-4-amino-5-hydroxymethylpyrimidine', 'Sequence': 'MKRINALTIAGTDPSGGAGIQADLKTFSALGAYGCSVITALVAQNTRGVQSVYRIEPDFVAAQLDSVFSDVRIDTTKIGMLAETDIVEAVAERLQRYQIQNVVLDTVMLAKSGDPLLSPSAVATLRSRLLPQVSLITPNLPEAAALLDAPHARTEQEMLEQGRSLLAMGCGAVLMKGGHLDDEQSPDWLFTREGEQRFTAPRIMTKNTHGTGCTLSAALAALRPRHTNWADTVQEAKSWLSSALAQADTLEVGHGIGPVHHFHAWW', 'Value': '0.43', 'Unit': 's^(-1)'}
{'ECNumber': '2.7.4.7', 'Organism': 'Escherichia coli', 'Smiles': 'CC1=NC=C(C(=N1)N)CO', 'Substrate': '2-methyl-4-amino-5-hydroxymethylpyrimidine', 'Sequence': 'MKRINALTIAGTDPSGGAGIQADLKTFSALGAYGCSVITALVAQNTRGVQSVYRIEPDFVAAQLDSVFSDVRIDTTKIGMLAETDIVEAVAERLQRYQIQNVVLDTVMLAKSGDPLLSPSAVATLRSRLLPQVSLITPNLPEAAALLDAPHARTEQEMLEQGRSLLAMGCGAVLMKGGHLDDEQSPDWLFTREGEQRFTAPRIMTKNTHGTGCTLSAALAALRPRHTNWADTVQEAKSWLSSALAQADTLEVGHGIGPVHHFHAWW', 'Value': '0.0867', 'Unit': 's^(-1)'}

If you check these two entries, you can find that they have different EC numbers and different kcat values. I guess this happened due to different measurements by different researchers, we are also not sure which one is the absolutely right one. But there are only quite a few data points like this!

For details about how we obtained and preprocessed the dataset from different resources, please check the method part and the related supplementary Figure 2. Thanks for your attention!

**Comment by jiejiangtao** [comment]
Thank you for your reply. I have read your data processing section and it is exactly what you said. Although some data have the same sequence and smile, their EC numbuber or organism are different.That is, although the sequence and organism are the same, there are others that are different, so it's not duplicate data. I think only sequence and smile are used in the code, but EC number, organism, etc.
{
        "ECNumber": "5.3.1.5",
        "Organism": "Streptomyces sp.",
        "Smiles": "C1C(C(C(C(O1)(CO)O)O)O)O",
        "Substrate": "D-Fructose",
        "Sequence": "RHAGSAHTF",
        "Value": "4.2",
        "Unit": "s^(-1)"
    },
   {
        "ECNumber": "5.3.1.5",
        "Organism": "Streptomyces sp.",
        "Smiles": "C(C1C(C(C(O1)(CO)O)O)O)O",
        "Substrate": "alpha-D-Fructofuranose",
        "Sequence": "RHAGSAHTF",
        "Value": "4.2",
        "Unit": "s^(-1)"
    },
However, there are also cases where the kcat value is the same, such as this one, but the substrate is different.

**Comment by le-yuan** [comment]
For this case, the same protein sequence with different substrates, it is also possible to have the same kcat value in biology.

**Comment by feiranl** [comment]
We have went through the process of removing duplicates. The combination of sequence and smiles are unique, but there are sequences which may matched to several smiles.
<img width="609" alt="Screenshot 2023-10-22 at 3 18 29 PM" src="https://github.com/SysBioChalmers/DLKcat/assets/32157802/3c64803b-6498-402c-9cbc-edccc890ac2c">
