### ISSUE TITLE
Data Missing - 343 Species

### ISSUE THREAD

**Issue by Frostday** [SysBioChalmers/DLKcat#4]
I am unable to run [predict_kcat_343_species.py](https://github.com/SysBioChalmers/DLKcat/blob/master/DeeplearningApproach/Code/prediction/predict_kcat_343_species.py) because the 343 species input data has not been provided inside [Data/input.zip](https://github.com/SysBioChalmers/DLKcat/blob/master/DeeplearningApproach/Data/input.zip) yet.
According to the code, there should be a folder named "kcatpredictionfile" containing all input data files for 343 species inside input.zip but I unzipped it and it was not present there.
Can you please tell me how to access this data?

**Comment by le-yuan** [comment]
Because the size of the input file for 343 species prediction is very large, it is impossible to put it into the GitHub repository. You can check our predicted results for 343 species on Zenodo: https://doi.org/10.5281/zenodo.6438262.

In addition, you can also check the Data availability section in our published papers. If you want to get access to other data in our work, you can also find them there.
