### ISSUE TITLE
您好，使用input例子prediction_for_input.py预测的Kcat是None

### ISSUE THREAD

**Issue by shadowlyu** [SysBioChalmers/DLKcat#5]
请问这个怎么解决呢，谢谢

**Comment by shadowlyu** [comment]
![mmexport1656133458265](https://user-images.githubusercontent.com/90537540/175758993-ff2d2524-2ff6-4556-a034-1e25630d09ad.png)
![mmexport1656133455905](https://user-images.githubusercontent.com/90537540/175758996-a837566f-9b32-4fc2-b6cb-d9c799b1a976.png)
![mmexport1656133458265](https://user-images.githubusercontent.com/90537540/175758998-02ef6de8-761d-4129-a97c-6c414f5b9648.png)

**Comment by le-yuan** [comment]
Hi, have you resolved this issue? Now that you can get the Kcat prediction result, I think you have installed all the packages successfully, or the program would throw out an error about "package not found". It is very weird that you got the result 'None' because many users can run the example easily across various systems. My suggestion is that: (1) Reinstall DLKcat and run the example again by yourself; (2) With the help from your colleagues, run DLKcat example using their computer; (3)you can debug the **prediction_for_input.py** file between line 231 and line 266 by using basic print function. If uncommon print is out, then you can know how did this issue happen.

**Comment by liudongliangHI** [comment]
I also encountered the same problem, but as the author said you can debug the prediction_for_input.py file between line 231 and line 266 by using basic print function. In short, you can try to modify line 267
``` 
           except:
                Kcat_value = 'None'
```
to
```
except Exception as e:
       print(repr(e))
       Kcat_value = 'None'
```

Then see what's wrong.

for me, Error is 
```
RuntimeError('Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)')
```
so, just change all tensors to be the same device, you can fix it.
```
fingerprints = torch.LongTensor(fingerprints).to(device)
adjacency = torch.FloatTensor(adjacency).to(device)
words = torch.LongTensor(words).to(device)
```

Of course, you may also encounter other error messages, and you need corresponding solutions.

**Comment by shadowlyu** [comment]
Thank you very much.

从 Windows 版邮件发送

发件人: feiranl
发送时间: 2022年6月24日 17:24
收件人: SysBioChalmers/DLKcat
抄送: shadowlyu; Author
主题: Re: [SysBioChalmers/DLKcat] 您好，使用input例子prediction_for_input.py预测的Kcat是None (Issue #5)

Could you print out the packages you have installed by running conda list or pip list?
